/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gq_malwarefight_nosession_linux_libc_Libc */

#ifndef _Included_gq_malwarefight_nosession_linux_libc_Libc
#define _Included_gq_malwarefight_nosession_linux_libc_Libc // NOLINT(bugprone-reserved-identifier)
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gq_malwarefight_nosession_linux_libc_Libc
 * Method:    geteuid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gq_malwarefight_nosession_linux_libc_Libc_geteuid
  (JNIEnv *, jclass);

/*
 * Class:     gq_malwarefight_nosession_linux_libc_Libc
 * Method:    unlink
 * Signature: (Ljava/lang/String;)
 */
JNIEXPORT void JNICALL Java_gq_malwarefight_nosession_linux_libc_Libc_unlink
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
