// Generated by build/write_buildflag_header.py
// From "//base:feature_list_buildflags"

#ifndef BASE_FEATURE_LIST_BUILDFLAGS_H_
#define BASE_FEATURE_LIST_BUILDFLAGS_H_

#include "build/buildflag.h" // IWYU pragma: export

#define BUILDFLAG_INTERNAL_ENABLE_BANNED_BASE_FEATURE_PREFIX() (0)

#endif  // BASE_FEATURE_LIST_BUILDFLAGS_H_
