// Generated by build/write_buildflag_header.py
// From "//base:logging_buildflags"

#ifndef BASE_LOGGING_BUILDFLAGS_H_
#define BASE_LOGGING_BUILDFLAGS_H_

#include "build/buildflag.h" // IWYU pragma: export

#define BUILDFLAG_INTERNAL_ENABLE_LOG_ERROR_NOT_REACHED() (0)
#define BUILDFLAG_INTERNAL_USE_RUNTIME_VLOG() (1)

#endif  // BASE_LOGGING_BUILDFLAGS_H_
