// Generated by build/write_buildflag_header.py
// From "//base:rust_buildflags"

#ifndef BASE_RUST_BUILDFLAGS_H_
#define BASE_RUST_BUILDFLAGS_H_

#include "build/buildflag.h" // IWYU pragma: export

#define BUILDFLAG_INTERNAL_BUILD_RUST_JSON_READER() (0)
#define BUILDFLAG_INTERNAL_BUILD_RUST_BASE_CONVERSIONS() (1)

#endif  // BASE_RUST_BUILDFLAGS_H_
