// Generated by build/write_buildflag_header.py
// From "//base:sanitizer_buildflags"

#ifndef BASE_SANITIZER_BUILDFLAGS_H_
#define BASE_SANITIZER_BUILDFLAGS_H_

#include "build/buildflag.h" // IWYU pragma: export

#define BUILDFLAG_INTERNAL_IS_HWASAN() (0)
#define BUILDFLAG_INTERNAL_USING_SANITIZER() (0)

#endif  // BASE_SANITIZER_BUILDFLAGS_H_
