// Generated by build/write_buildflag_header.py
// From "//base:tracing_buildflags"

#ifndef BASE_TRACING_BUILDFLAGS_H_
#define BASE_TRACING_BUILDFLAGS_H_

#include "build/buildflag.h" // IWYU pragma: export

#define BUILDFLAG_INTERNAL_ENABLE_BASE_TRACING() (1)
#define BUILDFLAG_INTERNAL_USE_PERFETTO_CLIENT_LIBRARY() (0)
#define BUILDFLAG_INTERNAL_USE_PERFETTO_TRACE_PROCESSOR() (0)
#define BUILDFLAG_INTERNAL_OPTIONAL_TRACE_EVENTS_ENABLED() (1)

#endif  // BASE_TRACING_BUILDFLAGS_H_
