name: Build with SLSA provenance
on:
  push: 
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      actions: read
    uses: pandaninjas/slsa-github-generator/.github/workflows/builder_gradle_slsa3.yml@patch-2-test
    with:
      artifact-list: ./build/libs/NoSession-GRADLE_VERSION.jar
      jdk-version: 8
      directory: .

